[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yadc"
version = "0.1.0"
description = "Yet Another Dataset Captioner"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests==2.32.5",
    "pillow==11.3.0",
    "pydantic==2.11.7",
    "toml>=0.10.2",
    "jinja2>=3.1.6",
    "keyring>=25.6.0",
]

[project.optional-dependencies]
dev = [
    "secretstorage>=3.4.0",
    "keyring-pass>=0.9.3",
]

[project.scripts]
yadc = "yadc.cli:main"

[tool.setuptools.package-data]
"yadc.templates" = ["*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["yadc*"]
