interactive = true

rounds = 1
overwrite_captions = true

[api]
url = "http://localhost:5001"
token = "" # add your api token here

[config]
max_tokens = 512

system_prompt = "You are a useful assistant."

user_prompt = """
Provide a long detailed description for this image. Don't mention something if it is not present in the image or doesn't exists in the image. You should keep the description within a paragraph, without losing important details.

Address the characters by their name. Always mention the name of the characters and the name of the artist. The artist name should be mentioned in the first sentence. The artist should be mentioned using phrases such as \"art by ARTIST\", \"digital illustration by ARTIST\", or a similar.
Artist name: {{ artist }}. Characters ({{ n_characters }} in the image): {{ characters }}.

{% if tags %}
These are the common tags for features of the characters in the image in random order. Use them for guidance but they might not be accurate or might not be for the same outfit as the one in the image:
{{ tags }}
{% endif %}

{% if context %}
The following is an accurate description of the image. It might miss details about the image, however you should always consider it as correct. Use the following for guidance when creating your description:
{{ context }}
{% endif %}
"""

[dataset]
caption_suffix = ".txt"

paths = [
    "you_image_path_here"
]


[[images]]
path = "path_to_an_existing_image"
artist = "artist name"
tags = "booru tags"
n_characters = 2
characters = "character_1, character_2"
context = "extra context used to guide the model"
